### ISSUE TITLE
I want to get the ID for Df(3R)BSC518, not the genes inside Df

### ISSUE THREAD

**Issue by rmd13** [hangnoh/flybaseR#1]
I want to get the ID for Df(3R)BSC518.
When I run

x = "Df(3R)BSC518
id.converter(x, symbols = F, bundle.size = 1000, DmelOnly = T, polite.access = 0, diehard.symbols = F, convert.into = "genes")

it returns a lisf of genes in that Df, but not the Df itself.

How to get the Df ID(FBab0045364)? 
I need the ID to make http address:
http://flybase.org/reports/FBab0045364
to do web request.

Thanks

**Comment by rmd13** [comment]
I got it:
just set the last args as empty
    out = c.eval('id.converter(x, symbols = F, bundle.size = 1000, DmelOnly = T, polite.access = 0, diehard.symbols = F, convert.into = "")');

**Comment by HJosephLee** [comment]
Oh, I see.  It is because your input was not a gene ID, but an ID for deficiencies (= deletions).  And, yes, the script should take what the second row of the FlyBase outcome, so should be working in such a case, but let me add a better function later.

**Comment by rmd13** [comment]
Dear hangnoh
Is it possible to write a function to input the fly stock number and get the plain genotype using R?
I have a list of fly stock number and majority of them are from Bloomington, and some of them from Tokyo, and for all these stock number I can find information on flybase.
 For example, input stock ID 11572 get the genptype:
	P{ry[+t7.2]=PZ}frc[02619] ry[506]/TM3, ry[RK] Sb[1] Ser[1]

Thanks
